

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /project

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource : "@UserBundle/Resources/config/routing.yml"
    prefix: /user
login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout